version: "3.8"
services:
  product-catalog-service:
    image: product-catalog-service:1.0.0-SNAPSHOT
    container_name: product-catalog-service
    hostname: product-catalog-service
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/product-catalog-service
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: