spring:
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
      preferIpAddress: true
    
server:
  port: 8761
  
debug: true  
